default: &default
  adapter: postgresql
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trivia_development

test:
  <<: *default
  database: trivia_test

production:
  <<: *default
  database: trivia_production
  username: trivia
  password: <%= ENV["TRIVIA_DATABASE_PASSWORD"] %>
